create schema soulmayte;
create extension pgcrypto;

create type soulmayte.relationship_status as enum (
  'single',
  'talking',
  'dating',
  'situationship',
  'relationship',
  'complicated'
);

create type soulmayte.looking_for_type as enum (
  'soulmate',
  'serious_relationship',
  'dating',
  'marriage',
  'clarity'
);

create table if not exists soulmayte.waitlist_entries (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  email text not null,
  full_name text,
  city text,
  state text,
  relationship_status soulmayte.relationship_status,
  looking_for soulmayte.looking_for_type,
  notes text,
  source text default 'landing_page'
);

create unique index if not exists soulmayte_waitlist_entries_email_key
  on soulmayte.waitlist_entries (lower(email));

-- Stores quiz submissions assessing user's relationship readiness
create table if not exists soulmayte.soulmate_readiness_quiz_submissions (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  email text not null,
  attachment_style text not null,
  communication_style text not null,
  long_term_intent text not null,
  -- Scores are percentages from 0 to 100
  self_awareness_score integer not null check (self_awareness_score between 0 and 100),
  emotional_availability_score integer not null check (emotional_availability_score between 0 and 100),
  values_alignment_score integer not null check (values_alignment_score between 0 and 100),
  notes text
);

-- Prevent duplicate quiz submissions from same email
create unique index if not exists soulmayte_quiz_submissions_email_key
  on soulmayte.soulmate_readiness_quiz_submissions (lower(email));

create table if not exists soulmayte.profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  created_at timestamptz not null default now(),
  email text not null unique,
  full_name text,
  city text,
  state text,
  bio text,
  dating_intention text
);

create table if not exists soulmayte.partner_profiles (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  partner_name text not null,
  notes text,
  relationship_stage text
);

-- Stores relationship analysis reports generated by AI
create table if not exists soulmayte.analysis_reports (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  email text,
  input_text text not null,
  compatibility_score integer check (compatibility_score between 0 and 100),
  risk_level text check (risk_level in ('low', 'moderate', 'high')),
  green_flags jsonb,
  red_flags jsonb,
  summary text,
  raw_ai_output jsonb
);

-- Enable RLS for analysis reports
alter table soulmayte.analysis_reports enable row level security;

-- Allow public users to create reports
drop policy if exists "analysis_reports_insert_public" on soulmayte.analysis_reports;
create policy "analysis_reports_insert_public"
on soulmayte.analysis_reports
for insert
to anon, authenticated
with check (true);

-- Service role has full access
drop policy if exists "analysis_reports_full_access_service_role" on soulmayte.analysis_reports;
create policy "analysis_reports_full_access_service_role"
on soulmayte.analysis_reports
for all
to service_role
using (true)
with check (true);

-- Enable Row Level Security for all tables
alter table soulmayte.waitlist_entries enable row level security;
alter table soulmayte.soulmate_readiness_quiz_submissions enable row level security; 
alter table soulmayte.profiles enable row level security;
alter table soulmayte.partner_profiles enable row level security;

-- Allow public users to join waitlist
drop policy if exists "public can insert waitlist entries" on soulmayte.waitlist_entries;
create policy "public can insert waitlist entries"
on soulmayte.waitlist_entries
for insert
to anon, authenticated
with check (true);

drop policy if exists "service role full access waitlist" on soulmayte.waitlist_entries;
create policy "service role full access waitlist"
on soulmayte.waitlist_entries
for all
to service_role
using (true)
with check (true);

-- Allow public users to submit quiz responses
drop policy if exists "public can insert quiz submissions" on soulmayte.soulmate_readiness_quiz_submissions;
create policy "public can insert quiz submissions"
on soulmayte.soulmate_readiness_quiz_submissions
for insert
to anon, authenticated
with check (true);

drop policy if exists "service role full access quiz submissions" on soulmayte.soulmate_readiness_quiz_submissions;
create policy "service role full access quiz submissions"
on soulmayte.soulmate_readiness_quiz_submissions
for all
to service_role
using (true)
with check (true);

-- Users can only access their own profile
drop policy if exists "users can view own profile" on soulmayte.profiles;
create policy "users can view own profile"
on soulmayte.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "users can insert own profile" on soulmayte.profiles;
create policy "users can insert own profile"
on soulmayte.profiles
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "users can update own profile" on soulmayte.profiles;
create policy "users can update own profile"
on soulmayte.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "users can manage own partner profiles" on soulmayte.partner_profiles;
create policy "users can manage own partner profiles"
on soulmayte.partner_profiles
for all
to authenticated
using (auth.uid() = owner_user_id)
with check (auth.uid() = owner_user_id);

grant usage on schema soulmayte to anon, authenticated, service_role;
-- Add indexes for commonly queried fields
create index if not exists analysis_reports_email_idx 
  on soulmayte.analysis_reports (email);

create index if not exists analysis_reports_created_at_idx 
  on soulmayte.analysis_reports (created_at);

grant all on all tables in schema soulmayte to anon, authenticated, service_role;
grant all on all sequences in schema soulmayte to anon, authenticated, service_role;
grant all on all routines in schema soulmayte to anon, authenticated, service_role;
